---
port: 80
# port: 443
listen_addr_port: 80
#servername: www.irb.ood.com
servername: www.irb.ood.irbbarcelona.pcb.ub.es
host_regex: 'irb(ccn|gcn)\d+.hpc.irbbarcelona.pcb.ub.es'
#host_regex: "[^/]+"
node_uri: '/node'
rnode_uri: '/rnode'
ssl: null
#  - 'SSLCertificateFile "/etc/pki/tls/certs/www_irb_ood_irbbarcelona_pcb_ub_es.crt"'
#  - 'SSLCertificateKeyFile "/etc/pki/tls/private/openondemand.key"'
#  - 'SSLCertificateChainFile "/etc/pki/tls/certs/www_irb_ood_irbbarcelona_pcb_ub_es_interm.crt"'
dex:
 frontend:

    theme: irb

    issuer: "IRB OnDemand"

    extra:
      loginTitle: "Log in with IRB username and pass"
      loginButtonText: "Log in"
      usernamePlaceholder: "Username"
      passwordPlaceholder: "Password"

 connectors:
   - type: ldap
     id: ldap
     name: Authentication node LDAP1
     config:
       host: irbldap1
       insecureNoSSL: true
       insecureSkipVerify: false
       #bindDN:
       #bindPW:
       userSearch:
         baseDN: o=irbbarcelona
         filter: "(objectClass=posixAccount)"
         username: uid
         idAttr: uid
         emailAttr: DN
         preferredUsernameAttr: uid
       groupSearch:
         baseDN: o=irbbarcelona
         filter: "(objectClass=posixGroup)"
         userMatchers:
           - userAttr: DN
             groupAttr: member
         nameAttr: cn

   - type: ldap
     id: ldap
     name: Authentication node LDAP2
     config:
       host: irbldap2
       insecureNoSSL: true
       insecureSkipVerify: false
       #bindDN:
       #bindPW:
       userSearch:
         baseDN: o=irbbarcelona
         filter: "(objectClass=posixAccount)"
         username: uid
         idAttr: uid
         emailAttr: DN
         preferredUsernameAttr: uid
       groupSearch:
         baseDN: o=irbbarcelona
         filter: "(objectClass=posixGroup)"
         userMatchers:
           - userAttr: DN
             groupAttr: member
         nameAttr: cn
